name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: eu-north-1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install AWS CLI
        run: |
          python -m pip install --upgrade pip
          pip install awscli

      - name: Install dependencies
        run: pip install --target=./ -r requirements.txt

      - name: Zip repository
        run: zip -r function.zip .

      - name: Upload zip file to AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name application_entry_point \
            --zip-file fileb://function.zip
