name: AWS Lambda Deployment

on:
  push:
    branches:
      - main

env:
  ATLAS_MONGODB_PASSWORD: ${{ secrets.ATLAS_MONGODB_PASSWORD }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }}
  AWS_CLOUDFRONT_DOMAIN_NAME: ${{ secrets.AWS_CLOUDFRONT_DOMAIN_NAME }}
  AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  aws_lambda_deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -t .

      - name: Build Deployment Zip File
        run: zip -r deployment.zip .

      - name: Deploy to AWS Lambda
        uses: appleboy/lambda-action@v0.1.9
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_region: eu-north-1
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          environment: |
            ATLAS_MONGODB_PASSWORD=${{ secrets.ATLAS_MONGODB_PASSWORD }},
            AWS_CLOUDFRONT_DISTRIBUTION_ID=${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }},
            AWS_CLOUDFRONT_DOMAIN_NAME=${{ secrets.AWS_CLOUDFRONT_DOMAIN_NAME }},
            AWS_S3_BUCKET=${{ secrets.AWS_S3_BUCKET }}
          function_name: application_entry_point
          memory_size: 128
          timeout: 30
          handler: app.handler.handler
          runtime: python3.9
          zip_file: deployment.zip
